version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  snyk:
    docker:
      - image: cimg/node:17.1.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run: node --version
      - run:
          name: Build Docker image
          command: docker build -t dylansnyk/demo-spring:latest -t dylansnyk/demo-spring:$CIRCLE_SHA1 .
      - run:
          name: Install Snyk
          command: npm install --prefix=$HOME/.local -g snyk
      - run:
          name: Snyk Open Source
          command: snyk test --severity-threshold=high
      - run:
          name: Snyk Code
          command: snyk code test --severity-threshold=high
      - run:
          name: Snyk Container
          command: snyk container test --severity-threshold=high dylansnyk/demo-spring:$CIRCLE_SHA1
      - run:
          name: Snyk IaC
          command: snyk iac test --severity-threshold=high

workflows:
  build-test-snyk:
    jobs:
      - build-and-test
      - snyk