name: Block Deep Code Ignore

on: push

jobs:
  block-deepcode-ignore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Search for "deepcode ignore"
        run: |
          if grep --exclude-dir .github -ri "deepcode ignore" . ; then
            echo "deepcode ignore found"
            exit 1
          else
            echo "deepcode ignore not found"
            exit 0
          fi

