name: Snyk Open Source

on:
  push:
    branches: [ develop, release ]

jobs:
  snyk-open-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Run Synk to scan for Maven vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif